language: ruby
sudo: false
rvm:
  - 2.3.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install: gem install jekyll jekyll-paginate html-proofer

script: jekyll build && htmlproofer --allow-hash-href --url-ignore "/www.tomesh.net/,/tomesh.net/" ./_site

notifications:
  email: false